--------------------------------------------------------
--  File created - vasárnap-március-05-2017   
--------------------------------------------------------
@/media/csaszika/csaszika/termeklapkeszito/deploy/DROP.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_ACTION_ID.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_ACTION_TYPE_ID.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_CUSTOMER_ID.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_TEMPLATE_ID.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/ST_TEMP_TO_ACTION.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_TYPE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_CUSTOMER.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_PRODUCT_SHEET_NUM.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_TEMPLATE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/ST_TEMP_TO_ACTION_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_TYPE_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_CUSTOMER_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_PRODUCT_SHEET_NUM_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_TEMPLATE_DATA_TABLE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/ACTION_NAME_UNIQUE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/CUSTOMER_NAME_UNIQUE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/PK_ACTION_TEMPLATE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/TEMPLATE_NAME_UNIQUE.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_TYPE_PK.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_CUSTOMER_PK.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_TYPE_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_PRODUCT_SHEET_NUM_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_CUSTOMER_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/ST_TEMP_TO_ACTION_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_TEMPLATE_CONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/ST_TEMP_TO_ACTION_REFCONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_ACTION_REFCONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/T_TEMPLATE_REFCONSTRAINT.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_ACTION_ID_GEN.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_ACTION_TYPE_ID_GEN.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_CUSTOMER_ID_GEN.sql
@/media/csaszika/csaszika/termeklapkeszito/deploy/SEQ_TEMPLATE_ID_GEN.sql
